### ISSUE TITLE
Unable to import dummy data

### ISSUE THREAD

**Issue by Hari-Bonda** [WordPress/wp-movies-demo#65]
Hello, thank you for providing this amazing test theme. I attempted to import test data, but unfortunately, it failed.

WP version 6.5

![image](https://github.com/WordPress/wp-movies-demo/assets/5230394/bb3c0901-5f80-4878-b64e-05188b1359f0)

**Comment by cbravobernal** [comment]
Hi there! 

You need to activate the plugin `WP Movies` included in the repository that will create the post type actors.
